services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ftse
    environment:
      POSTGRES_USER: ftse
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - data_sql:/var/lib/postgresql/data   # Persistent data storage
    ports:
      - "5432:5432"

volumes:
  data_sql: