GET http://localhost:8080/starter/api/customers/1

###
GET http://localhost:8080/starter/api/customers

###
POST http://localhost:8080/starter/api/customers
Content-Type: application/json

{
  "geburtsdatum": "2010-10-08T15:06:04.910603681",
  "nachname": "based",
  "vorname": "say"
}

###
PATCH http://localhost:8080/starter/api/customers/1
Content-Type: application/json

{
  "geburtsdatum": "2010-10-08T15:06:04.910603681",
  "nachname": "epic",
  "vorname": "say"
}

###
DELETE http://localhost:8080/starter/api/customers/1
