GET http://localhost:8080/starter/api/helloworld

###
DELETE http://localhost:8080/starter/api/helloworld

###
PUT http://localhost:8080/starter/api/helloworld
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###
OPTIONS http://localhost:8080/starter/api/helloworld


###
HEAD http://localhost:8080/starter/api/helloworld