GET http://localhost:8080/starter/api/helloworld

###
DELETE http://localhost:8080/starter/api/helloworld

###
PUT http://localhost:8080/starter/api/helloworld
Content-Type: application/json

{
  "test": 123
}

###
PATCH http://localhost:8080/starter/api/helloworld
Content-Type: application/json

{
  "test": 456
}
###
POST http://localhost:8080/starter/api/helloworld
Content-Type: application/json

{
  "test": 789
}
###
OPTIONS http://localhost:8080/starter/api/helloworld


###
HEAD http://localhost:8080/starter/api/helloworld